### ISSUE TITLE
Private config repository means dashv2 can't build on Travis

### ISSUE THREAD

**Issue by dmolesUC3** [CDLUC3/dashv2#1]
See e.g. https://travis-ci.org/CDLUC3/dashv2/builds/105235626

Is there a way we can move a complete minimal configuration into the application and make the secret/local stuff optional?

```
/home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - /home/travis/build/CDLUC3/dashv2/config/app_config.yml (Errno::ENOENT)
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:464:in `open'
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/psych.rb:464:in `load_file'
    from /home/travis/build/CDLUC3/dashv2/config/initializers/app_config.rb:5:in `<top (required)>'
    from /home/travis/build/CDLUC3/dashv2/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
    from /home/travis/build/CDLUC3/dashv2/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
    from /home/travis/build/CDLUC3/dashv2/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
```

**Comment by dmolesUC3** [comment]
[Running integration tests in Travis](https://travis-ci.org/CDLUC3/dashv2) since June 2017 or so.
